void config_pwm(float Tpwm);
void set_period(float Tpwm);
float pwm_get_period();
void set_duty_pwm(float izq, float dch);
float pwm_get_duty_cycle(int wheel);
void para_pwm(int wheel);
void enc_config();
void enc_set_dist_limit(int dist_cm, int wheel);
void enc_set_angle_limit(float angle_robot, int wheel);
float enc_get_dist(int wheel);
void battery_sampling_init(float Ts);
void battery_sampling_stop(void);
void alarm_init(void);
void alarm_gen_sample(void);
void alarm_set_freq(int frq_hz);
void alarm_enable(int enable);
int uart0_cfg(int baudrate);
int uart0_send_string(const char *s);
int uart0_get_tx_busy();
int uart0_recv_string(char *txt);
int uart0_get_rx_busy();
